services:
  phpfpm:
    environment:
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_MEMORY_LIMIT=512M

  nginx:
    environment:
      # Match PHP_MAX_EXECUTION_TIME above
      - NGINX_FASTCGI_READ_TIMEOUT=300

  node:
    image: node:20
    working_dir: /app
    networks:
      - app
    volumes:
      - ./web/profiles/custom/os2loop/themes/os2loop_theme:/app
