services:
  phpfpm:
    volumes:
      - ../../shared/settings.local.php:/app/web/sites/default/settings.local.php
      - ../../shared/files:/app/web/sites/default/files

  nginx:
    volumes:
      - ../../shared/files:/app/web/sites/default/files
