services:
  os2loop_settings.settings:
    class: Drupal\os2loop_settings\Settings
    arguments:
      - '@config.factory'
      - '@entity_type.manager'

  os2loop_settings.helper:
    class: Drupal\os2loop_settings\Helper\Helper
    arguments:
      - '@os2loop_settings.settings'
      - '@messenger'

  os2loop_settings.twig_extension:
    class: Drupal\os2loop_settings\TwigExtension\TwigExtension
    arguments:
      - '@current_user'
      - '@module_handler'
    tags:
      - { name: twig.extension }
