os2loop.group.admin:
  title: 'OS2Loop'
  route_name: os2loop_settings.admin
  parent: system.admin_config
  description: 'OS2Loop settings'
  weight: -999

os2loop.admin_settings:
  title: 'OS2Loop settings'
  route_name: os2loop_settings.settings
  description: 'Configure OS2Loop settings'
  # parent: system.admin_config_system
  parent: os2loop.group.admin
  weight: 0
