when:
  - event: release

skip_clone: true

labels:
  zone: CLOUD

steps:
  - name: Ansible playbook
    image: itkdev/ansible-plugin:1
    pull: true
    settings:
      id:
        from_secret: id
      secret:
        from_secret: secret
      host:
        from_secret: prod_os2forms_host
      path:
        from_secret: prod_os2forms_path
      user:
        from_secret: user
      playbook: 'release'
      pre_up:
        # Fixes issue with 'Drupal\mysql\Driver\Database\mysql\Connection' not found
        - itkdev-docker-compose-server run --rm phpfpm composer2 dump-autoload
        - itkdev-docker-compose-server run --rm phpfpm vendor/bin/drush --yes cache:rebuild
        - itkdev-docker-compose-server run --rm phpfpm vendor/bin/drush --yes deploy
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:update
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import --type=customized --override=none da /app/web/profiles/custom/os2loop/translations/translations.da.po
        - itkdev-docker-compose-server run --rm phpfpm vendor/bin/drush --yes cache:rebuild
      cron:
        cron:
          minute: '47'
          hour: '*'
          day: '*'
          month: '*'
          weekday: '*'
          job: 'itkdev-docker-compose-server exec phpfpm vendor/bin/drush core:cron'
