when:
  - branch: release/*
    event: push

skip_clone: true

labels:
  zone: DMZ

steps:
  - name: Run staging site update
    image: itkdev/ansible-plugin:1
    pull: true
    settings:
      id:
        from_secret: id
      secret:
        from_secret: secret
      host:
        from_secret: stg_host
      path:
        from_secret: stg_path
      user:
        from_secret: user
      actions:
        - chmod +w web/sites/default
        - chmod +w web/sites/default/settings.php
        - git reset --hard
        - git fetch origin ${CI_COMMIT_BRANCH}
        - git checkout ${CI_COMMIT_BRANCH}
        - git pull
        - itkdev-docker-compose-server up -d --force-recreate
        # Build theme
        - itkdev-docker-compose-server run --rm node yarn install
        - itkdev-docker-compose-server run --rm node yarn build
        - itkdev-docker-compose-server run --rm node rm -rf node_modules
        # Ensure everything is owned by deploy
        - sudo chown -R deploy:deploy web
        # Deploy site.
        - itkdev-docker-compose-server exec phpfpm composer install --no-interaction
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes deploy
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:update
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import --type=customized --override=none da /app/web/profiles/custom/os2loop/translations/translations.da.po
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes cache:rebuild
